name: Welcome Comment

on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read comment from markdown file
        id: read
        run: |
          COMMENT=$(cat .github/assets/pull-request-landing.md)
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post welcome comment
        uses: zunalita-archives/pull-request-landing@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment: "${{ steps.read.outputs.comment }}"
