name: Send landing message to pull request.

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read welcome message from file
        id: read_message
        run: |
          content=$(cat .github/assets/pull-request-landing.md)
          # Escape line breaks for JSON
          content="${content//$'\n'/\\n}"
          echo "content=$content" >> $GITHUB_OUTPUT

      - name: Post welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const content = `${{ steps.read_message.outputs.content }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: content
            });